In [3]:
import os
import pandas as pd

In [6]:
[x for x in os.listdir('./data') if 'Trips' in x]

['Divvy_Trips_2017_Q1.csv', 'Divvy_Trips_2017_Q2.csv']

In [25]:
trips = pd.DataFrame()

for i in [x for x in os.listdir('./data') if 'Trips' in x]:
    ## Figure out quarter by delimiting string
    quarter = i.split("_")[3].split(".")[0]
    df = pd.read_csv('./data/' + i)
    df['quarter'] = quarter
    
    trips = trips.append(df)

In [47]:
trips.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
trip_id,1551505.0,1.393174e+07,540393.289845,12979230.0,13465468.0,13938475.0,14403519.0,14853213.0
bikeid,1551505.0,3.159740e+03,1728.395379,1.0,1657.0,3318.0,4689.0,5920.0
tripduration,1551505.0,9.397778e+02,1617.701777,60.0,392.0,670.0,1127.0,86338.0
from_station_id,1551505.0,1.793282e+02,131.892696,2.0,74.0,153.0,268.0,623.0
to_station_id,1551505.0,1.794676e+02,131.991760,2.0,74.0,153.0,268.0,623.0
birthyear,1234822.0,1.980864e+03,10.991542,1899.0,1975.0,1984.0,1989.0,2016.0

In [39]:
## Columns containing null
trips.isnull().any()

trip_id              False
start_time           False
end_time             False
bikeid               False
tripduration         False
from_station_id      False
from_station_name    False
to_station_id        False
to_station_name      False
usertype             False
gender                True
birthyear             True
quarter              False
dtype: bool

In [38]:
## Rows with null values
trips[trips.isnull().any(axis=1)]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear,quarter
32,13518872,3/31/2017 23:19:53,3/31/2017 23:34:08,3237,855,210,Ashland Ave & Division St,77,Clinton St & Madison St,Customer,NaN,NaN,Q1
56,13518848,3/31/2017 22:53:31,3/31/2017 23:15:14,242,1303,81,Daley Center Plaza,172,Rush St & Cedar St,Customer,NaN,NaN,Q1
59,13518845,3/31/2017 22:52:18,3/31/2017 23:15:14,182,1376,81,Daley Center Plaza,172,Rush St & Cedar St,Customer,NaN,NaN,Q1
61,13518843,3/31/2017 22:52:02,3/31/2017 23:07:14,5453,912,2,Buckingham Fountain,39,Wabash Ave & Adams St,Customer,NaN,NaN,Q1
63,13518841,3/31/2017 22:51:56,3/31/2017 23:07:14,1752,918,2,Buckingham Fountain,39,Wabash Ave & Adams St,Customer,NaN,NaN,Q1
64,13518840,3/31/2017 22:51:49,3/31/2017 23:07:18,5003,929,2,Buckingham Fountain,39,Wabash Ave & Adams St,Customer,NaN,NaN,Q1
65,13518839,3/31/2017 22:51:39,3/31/2017 23:07:35,1848,956,2,Buckingham Fountain,39,Wabash Ave & Adams St,Customer,NaN,NaN,Q1
68,13518836,3/31/2017 22:50:41,3/31/2017 23:15:35,461,1494,81,Daley Center Plaza,172,Rush St & Cedar St,Customer,NaN,NaN,Q1
70,13518834,3/31/2017 22:48:23,3/31/2017 23:04:51,2211,988,195,Columbus Dr & Randolph St,181,LaSalle St & Illinois St,Customer,NaN,NaN,Q1
83,13518820,3/31/2017 22:32:14,3/31/2017 22:44:10,5202,716,537,Kenton Ave & Madison St,530,Laramie Ave & Kinzie St,Customer,NaN,NaN,Q1
90,13518813,3/31/2017 22:26:43,3/31/2017 22:49:46,5148,1383,284,Michigan Ave & Jackson Blvd,2,Buckingham Fountain,Customer,NaN,NaN,Q1
92,13518811,3/31/2017 22:25:36,3/31/2017 22:50:11,1800,1475,284,Michigan Ave & Jackson Blvd,2,Buckingham Fountain,Customer,NaN,NaN,Q1
93,13518810,3/31/2017 22:25:21,3/31/2017 22:50:38,2219,1517,284,Michigan Ave & Jackson Blvd,2,Buckingham Fountain,Customer,NaN,NaN,Q1
94,13518809,3/31/2017 22:25:10,3/31/2017 22:49:40,1354,1470,284,Michigan Ave & Jackson Blvd,2,Buckingham Fountain,Customer,NaN,NaN,Q1
100,13518803,3/31/2017 22:21:58,3/31/2017 22:29:30,2936,452,195,Columbus Dr & Randolph St,174,Canal St & Madison St,Customer,NaN,NaN,Q1
106,13518797,3/31/2017 22:18:05,3/31/2017 22:30:43,2377,758,161,Rush St & Superior St,86,Eckhart Park,Customer,NaN,NaN,Q1
107,13518796,3/31/2017 22:18:00,3/31/2017 22:30:33,4310,753,161,Rush St & Superior St,86,Eckhart Park,Customer,NaN,NaN,Q1
113,13518790,3/31/2017 22:12:22,3/31/2017 22:21:50,1799,568,45,Michigan Ave & Congress Pkwy,45,Michigan Ave & Congress Pkwy,Customer,NaN,NaN,Q1
115,13518788,3/31/2017 22:11:45,3/31/2017 22:21:25,4569,580,45,Michigan Ave & Congress Pkwy,45,Michigan Ave & Congress Pkwy,Customer,NaN,NaN,Q1
116,13518787,3/31/2017 22:11:21,3/31/2017 22:21:50,2411,629,45,Michigan Ave & Congress Pkwy,45,Michigan Ave & Congress Pkwy,Customer,NaN,NaN,Q1
117,13518786,3/31/2017 22:10:43,3/31/2017 22:28:06,3547,1043,62,McCormick Place,33,State St & Van Buren St,Customer,NaN,NaN,Q1
119,13518784,3/31/2017 22:07:56,3/31/2017 22:16:21,3821,505,215,Damen Ave & Madison St,198,Green St & Madison St,Customer,NaN,NaN,Q1
121,13518782,3/31/2017 22:07:39,3/31/2017 22:16:46,2481,547,215,Damen Ave & Madison St,198,Green St & Madison St,Customer,NaN,NaN,Q1
124,13518779,3/31/2017 22:06:34,3/31/2017 22:16:26,3351,592,215,Damen Ave & Madison St,198,Green St & Madison St,Customer,NaN,NaN,Q1
125,13518778,3/31/2017 22:05:06,3/31/2017 22:21:47,1454,1001,172,Rush St & Cedar St,331,Halsted St & Blackhawk St (*),Customer,NaN,NaN,Q1
126,13518777,3/31/2017 22:04:58,3/31/2017 22:22:00,3133,1022,172,Rush St & Cedar St,331,Halsted St & Blackhawk St (*),Customer,NaN,NaN,Q1
132,13518771,3/31/2017 22:02:23,3/31/2017 22:37:31,5453,2108,2,Buckingham Fountain,2,Buckingham Fountain,Customer,NaN,NaN,Q1
135,13518768,3/31/2017 22:01:25,3/31/2017 22:37:31,5003,2166,2,Buckingham Fountain,2,Buckingham Fountain,Customer,NaN,NaN,Q1
147,13518756,3/31/2017 21:54:17,3/31/2017 22:10:21,2431,964,35,Streeter Dr & Grand Ave,2,Buckingham Fountain,Customer,NaN,NaN,Q1
149,13518754,3/31/2017 21:53:15,3/31/2017 22:10:21,4082,1026,35,Streeter Dr & Grand Ave,2,Buckingham Fountain,Customer,NaN,NaN,Q1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1119400,13519338,4/1/2017 08:43:41,4/1/2017 10:51:10,3276,7649,451,Sheridan Rd & Loyola Ave,85,Michigan Ave & Oak St,Customer,NaN,NaN,Q2
1119403,13519335,4/1/2017 08:42:50,4/1/2017 09:01:30,4757,1120,195,Columbus Dr & Randolph St,4,Burnham Harbor,Customer,NaN,NaN,Q2
1119407,13519331,4/1/2017 08:41:44,4/1/2017 08:46:56,1711,312,51,Clark St & Randolph St,133,Kingsbury St & Kinzie St,Customer,NaN,NaN,Q2
1119422,13519316,4/1/2017 08:38:33,4/1/2017 08:55:12,409,999,480,Albany (Kedzie) Ave & Montrose Ave,246,Ashland Ave & Belle Plaine Ave,Customer,NaN,NaN,Q2
1119427,13519310,4/1/2017 08:36:12,4/1/2017 08:51:18,2328,906,161,Rush St & Superior St,49,Dearborn St & Monroe St,Customer,NaN,NaN,Q2
1119447,13519288,4/1/2017 08:30:08,4/1/2017 08:55:30,4748,1522,2,Buckingham Fountain,268,Lake Shore Dr & North Blvd,Customer,NaN,NaN,Q2
1119451,13519284,4/1/2017 08:28:08,4/1/2017 08:55:20,2219,1632,2,Buckingham Fountain,268,Lake Shore Dr & North Blvd,Customer,NaN,NaN,Q2
1119500,13519231,4/1/2017 08:10:55,4/1/2017 08:45:48,3275,2093,289,Wells St & Concord Ln,338,Calumet Ave & 18th St,Customer,NaN,NaN,Q2
1119514,13519217,4/1/2017 08:06:11,4/1/2017 08:14:17,5063,486,303,Broadway & Cornelia Ave,156,Clark St & Wellington Ave,Customer,NaN,NaN,Q2
1119522,13519209,4/1/2017 08:04:20,4/1/2017 08:36:28,4599,1928,35,Streeter Dr & Grand Ave,35,Streeter Dr & Grand Ave,Customer,NaN,NaN,Q2
1119523,13519208,4/1/2017 08:04:00,4/1/2017 08:36:28,4698,1948,35,Streeter Dr & Grand Ave,35,Streeter Dr & Grand Ave,Customer,NaN,NaN,Q2
1119530,13519198,4/1/2017 07:56:56,4/1/2017 08:05:22,2271,506,118,Sedgwick St & North Ave,53,Wells St & Huron St,Customer,NaN,NaN,Q2
1119584,13519142,4/1/2017 07:37:28,4/1/2017 07:51:26,3779,838,45,Michigan Ave & Congress Pkwy,62,McCormick Place,Customer,NaN,NaN,Q2
1119617,13519107,4/1/2017 07:06:20,4/1/2017 07:31:45,2964,1525,459,Lakefront Trail & Bryn Mawr Ave,459,Lakefront Trail & Bryn Mawr Ave,Customer,NaN,NaN,Q2
1119650,13519074,4/1/2017 06:10:48,4/1/2017 07:05:14,2775,3266,597,Chicago Ave & Washington St,85,Michigan Ave & Oak St,Customer,NaN,NaN,Q2
1119688,13519035,4/1/2017 03:46:21,4/1/2017 03:54:03,1140,462,47,State St & Kinzie St,195,Columbus Dr & Randolph St,Customer,NaN,NaN,Q2
1119697,13519026,4/1/2017 02:40:34,4/1/2017 02:51:59,4632,685,123,California Ave & Milwaukee Ave,123,California Ave & Milwaukee Ave,Customer,NaN,NaN,Q2
1119712,13519011,4/1/2017 02:01:38,4/1/2017 04:06:46,1528,7508,86,Eckhart Park,62,McCormick Place,Customer,NaN,NaN,Q2
1119713,13519010,4/1/2017 02:01:19,4/1/2017 04:06:39,4072,7520,86,Eckhart Park,62,McCormick Place,Customer,NaN,NaN,Q2
1119716,13519005,4/1/2017 01:56:01,4/1/2017 02:02:54,5578,413,43,Michigan Ave & Washington St,45,Michigan Ave & Congress Pkwy,Customer,NaN,NaN,Q2
1119717,13519004,4/1/2017 01:55:38,4/1/2017 02:02:50,2989,432,43,Michigan Ave & Washington St,45,Michigan Ave & Congress Pkwy,Customer,NaN,NaN,Q2
1119719,13519002,4/1/2017 01:55:22,4/1/2017 02:02:50,3779,448,43,Michigan Ave & Washington St,45,Michigan Ave & Congress Pkwy,Customer,NaN,NaN,Q2
1119729,13518992,4/1/2017 01:37:21,4/1/2017 01:39:28,4270,127,242,Damen Ave & Leland Ave,344,Ravenswood Ave & Lawrence Ave,Customer,NaN,NaN,Q2
1119733,13518988,4/1/2017 01:30:08,4/1/2017 01:53:38,1463,1410,90,Millennium Park,43,Michigan Ave & Washington St,Customer,NaN,NaN,Q2
1119734,13518987,4/1/2017 01:29:56,4/1/2017 01:53:51,1904,1435,90,Millennium Park,43,Michigan Ave & Washington St,Customer,NaN,NaN,Q2
1119735,13518986,4/1/2017 01:29:36,4/1/2017 01:54:09,5371,1473,90,Millennium Park,43,Michigan Ave & Washington St,Customer,NaN,NaN,Q2
1119755,13518966,4/1/2017 01:08:47,4/1/2017 01:28:01,1799,1154,45,Michigan Ave & Congress Pkwy,90,Millennium Park,Customer,NaN,NaN,Q2
1119756,13518965,4/1/2017 01:08:40,4/1/2017 01:27:38,4645,1138,45,Michigan Ave & Congress Pkwy,90,Millennium Park,Customer,NaN,NaN,Q2
1119757,13518964,4/1/2017 01:07:49,4/1/2017 01:27:36,2411,1187,45,Michigan Ave & Congress Pkwy,90,Millennium Park,Customer,NaN,NaN,Q2
1119771,13518950,4/1/2017 00:44:42,4/1/2017 00:53:52,947,550,324,Stockton Dr & Wrightwood Ave,324,Stockton Dr & Wrightwood Ave,Customer,NaN,NaN,Q2

In [85]:
import sqlalchemy

engine = sqlalchemy.create_engine('postgresql://waihamyee@localhost:5432/divvy')
conn = engine.raw_connection()

In [ ]:
trips.to_sql("trips", engine, if_exists="replace")

In [75]:
stations = pd.read_csv('./data/Divvy_Stations_2017_Q1Q2.csv')

In [81]:
stations.isnull().any()

id             False
name           False
city           False
latitude       False
longitude      False
dpcapacity     False
online_date    False
dtype: bool

In [84]:
stations.columns

Index([u'id', u'name', u'city', u'latitude', u'longitude', u'dpcapacity',
       u'online_date'],
      dtype='object')

In [78]:
stations.to_sql("stations", engine, if_exists="replace")

In [156]:
connection = engine.connect()
from sqlalchemy.sql import text
s = text(
     "SELECT MAX(c)" 
     "FROM"
         "(SELECT COUNT(1) AS c "
          "FROM trips "
          "WHERE to_date(start_time, 'MM/DD/YYYY') < to_date(:d, 'MM/DD/YYYY')"
          "GROUP BY to_date(start_time, 'MM/DD/YYYY HH24:MI:SS')) a"
    )
print connection.execute(s, d='02/07/2017').fetchone()
connection.close()

(7697L,)

In [157]:
connection = engine.connect()
s = text(
     "SELECT COUNT(1) "
     "FROM trips "
     "WHERE tripduration > :c"
    )
print connection.execute(s, c=10000).fetchone()
connection.close()

(3390L,)

In [182]:
connection = engine.connect()
s = text(
     "SELECT " 
     "COUNT (CASE WHEN tripduration/(60) >= 0 AND tripduration/(60) <= 10 THEN 1 END) AS \"0-10min\","
     "COUNT (CASE WHEN tripduration/(60) > 10 AND tripduration/(60) <= 20 THEN 1 END) AS \"10-20min\","
     "COUNT (CASE WHEN tripduration/(60) > 20 AND tripduration/(60) <= 30 THEN 1 END) AS \"20-30min\","
     "COUNT (CASE WHEN tripduration/(60) > 30 AND tripduration/(60) <= 60 THEN 1 END) AS \"30-60min\","
     "COUNT (CASE WHEN tripduration/(60) > 60 AND tripduration/(60) <= 120 THEN 1 END) AS \"1-2hr\","
     "COUNT (CASE WHEN tripduration/(60) > 120 AND tripduration/(60) <= (60*12) THEN 1 END) AS \"2-12hr\","
     "COUNT (CASE WHEN tripduration/(60) > (60*12) AND tripduration/(60) <= (60*24) THEN 1 END) AS \"12-24hr\" "
     "FROM trips"
    )
results = list(connection.execute(s).fetchone())
connection.close()

In [187]:
import plotly.plotly as py
import plotly.graph_objs as go

print results

data = [go.Bar(
            x=['0-10','10-20','20-30','30-60','1-2hr','2-12hr','12-24hr'],
            y=results
    )]

layout = go.Layout(
    yaxis=dict(
        type='log',
        autorange=True
    ))

fig = go.Figure(data=data, layout=layout)
py.iplot(fig)

[763969L, 474782L, 203005L, 80223L, 22450L, 6561L, 515L]